// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyumAb71LSKbpqPFhLmi0e3jMX7rLHVIY',
    appId: '1:463314394010:web:7bb790e310dff9f29d3823',
    messagingSenderId: '463314394010',
    projectId: 'loquetoca-e9688',
    authDomain: 'loquetoca-e9688.firebaseapp.com',
    storageBucket: 'loquetoca-e9688.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiOudALoGVaT1gYhiU5I5fL0v4u6YJ-nk',
    appId: '1:463314394010:android:d0fd93c7024e1c9d9d3823',
    messagingSenderId: '463314394010',
    projectId: 'loquetoca-e9688',
    storageBucket: 'loquetoca-e9688.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBejtfiC-MaV_LjjhaOHXrIG9hA5Wp8Nn4',
    appId: '1:463314394010:ios:b7aa91c9575a24ec9d3823',
    messagingSenderId: '463314394010',
    projectId: 'loquetoca-e9688',
    storageBucket: 'loquetoca-e9688.firebasestorage.app',
    iosBundleId: 'com.example.loquetoca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBejtfiC-MaV_LjjhaOHXrIG9hA5Wp8Nn4',
    appId: '1:463314394010:ios:b7aa91c9575a24ec9d3823',
    messagingSenderId: '463314394010',
    projectId: 'loquetoca-e9688',
    storageBucket: 'loquetoca-e9688.firebasestorage.app',
    iosBundleId: 'com.example.loquetoca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyumAb71LSKbpqPFhLmi0e3jMX7rLHVIY',
    appId: '1:463314394010:web:0e4bea0ac8e92e349d3823',
    messagingSenderId: '463314394010',
    projectId: 'loquetoca-e9688',
    authDomain: 'loquetoca-e9688.firebaseapp.com',
    storageBucket: 'loquetoca-e9688.firebasestorage.app',
  );
}
